# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build
        run: nix develop -c ./create_nar.sh
      - name: Upload the artifact
        uses: actions/upload-artifact@v7
        with:
          path: ghost_in_a_nutshell.nar
          archive: false
